# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MIDI_QT1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.C_3 = QtWidgets.QPushButton(self.centralwidget)
        self.C_3.setGeometry(QtCore.QRect(280, 370, 101, 271))
        self.C_3.setText("")
        self.C_3.setObjectName("C_3")
        self.D_3 = QtWidgets.QPushButton(self.centralwidget)
        self.D_3.setGeometry(QtCore.QRect(380, 370, 101, 271))
        self.D_3.setText("")
        self.D_3.setObjectName("D_3")
        self.E_3 = QtWidgets.QPushButton(self.centralwidget)
        self.E_3.setGeometry(QtCore.QRect(480, 370, 101, 271))
        self.E_3.setText("")
        self.E_3.setObjectName("E_3")
        self.F_3 = QtWidgets.QPushButton(self.centralwidget)
        self.F_3.setGeometry(QtCore.QRect(580, 370, 101, 271))
        self.F_3.setText("")
        self.F_3.setObjectName("F_3")
        self.G_3 = QtWidgets.QPushButton(self.centralwidget)
        self.G_3.setGeometry(QtCore.QRect(680, 370, 101, 271))
        self.G_3.setText("")
        self.G_3.setObjectName("G_3")
        self.A_3 = QtWidgets.QPushButton(self.centralwidget)
        self.A_3.setGeometry(QtCore.QRect(780, 370, 101, 271))
        self.A_3.setText("")
        self.A_3.setObjectName("A_3")
        self.B_3 = QtWidgets.QPushButton(self.centralwidget)
        self.B_3.setGeometry(QtCore.QRect(880, 370, 101, 271))
        self.B_3.setText("")
        self.B_3.setObjectName("B_3")
        self.Db3 = QtWidgets.QPushButton(self.centralwidget)
        self.Db3.setGeometry(QtCore.QRect(350, 370, 71, 151))
        self.Db3.setText("")
        self.Db3.setObjectName("Db3")
        self.Eb3 = QtWidgets.QPushButton(self.centralwidget)
        self.Eb3.setGeometry(QtCore.QRect(440, 370, 71, 151))
        self.Eb3.setText("")
        self.Eb3.setObjectName("Eb3")
        self.Gb3 = QtWidgets.QPushButton(self.centralwidget)
        self.Gb3.setGeometry(QtCore.QRect(650, 370, 71, 151))
        self.Gb3.setText("")
        self.Gb3.setObjectName("Gb3")
        self.Ab3 = QtWidgets.QPushButton(self.centralwidget)
        self.Ab3.setGeometry(QtCore.QRect(750, 370, 71, 151))
        self.Ab3.setText("")
        self.Ab3.setObjectName("Ab3")
        self.Bb3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb3.setGeometry(QtCore.QRect(850, 370, 71, 151))
        self.Bb3.setText("")
        self.Bb3.setObjectName("Bb3")
        self.choose_soundbank = QtWidgets.QPushButton(self.centralwidget)
        self.choose_soundbank.setGeometry(QtCore.QRect(10, 10, 171, 91))
        self.choose_soundbank.setObjectName("choose_soundbank")
        self.record_btn = QtWidgets.QPushButton(self.centralwidget)
        self.record_btn.setGeometry(QtCore.QRect(1000, 0, 141, 101))
        self.record_btn.setObjectName("record_btn")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(1140, 0, 131, 101))
        self.play_btn.setObjectName("play_btn")
        self.error_lbl = QtWidgets.QLabel(self.centralwidget)
        self.error_lbl.setGeometry(QtCore.QRect(500, 650, 251, 31))
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.prev_oct = QtWidgets.QPushButton(self.centralwidget)
        self.prev_oct.setGeometry(QtCore.QRect(20, 560, 131, 91))
        self.prev_oct.setObjectName("prev_oct")
        self.next_oct = QtWidgets.QPushButton(self.centralwidget)
        self.next_oct.setGeometry(QtCore.QRect(1120, 560, 131, 91))
        self.next_oct.setObjectName("next_oct")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 320, 51, 41))
        self.label.setObjectName("label")
        self.oct = QtWidgets.QSpinBox(self.centralwidget)
        self.oct.setGeometry(QtCore.QRect(650, 330, 42, 22))
        self.oct.setMinimum(-1)
        self.oct.setMaximum(8)
        self.oct.setProperty("value", -1)
        self.oct.setObjectName("oct")
        self.gr_piano = QtWidgets.QRadioButton(self.centralwidget)
        self.gr_piano.setGeometry(QtCore.QRect(30, 110, 101, 20))
        self.gr_piano.setObjectName("gr_piano")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.gr_piano)
        self.piano_col = QtWidgets.QRadioButton(self.centralwidget)
        self.piano_col.setGeometry(QtCore.QRect(30, 140, 131, 20))
        self.piano_col.setObjectName("piano_col")
        self.buttonGroup.addButton(self.piano_col)
        self.ac_guitar = QtWidgets.QRadioButton(self.centralwidget)
        self.ac_guitar.setGeometry(QtCore.QRect(30, 170, 121, 20))
        self.ac_guitar.setObjectName("ac_guitar")
        self.buttonGroup.addButton(self.ac_guitar)
        self.user_sb = QtWidgets.QRadioButton(self.centralwidget)
        self.user_sb.setGeometry(QtCore.QRect(30, 210, 141, 20))
        self.user_sb.setObjectName("user_sb")
        self.buttonGroup.addButton(self.user_sb)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_soundbank.setText(_translate("MainWindow", "Choose Soundbank"))
        self.record_btn.setText(_translate("MainWindow", "Start a recording"))
        self.play_btn.setText(_translate("MainWindow", "Play a record"))
        self.prev_oct.setText(_translate("MainWindow", "Previous Octave"))
        self.next_oct.setText(_translate("MainWindow", "Next Octave"))
        self.label.setText(_translate("MainWindow", "Octave:"))
        self.gr_piano.setText(_translate("MainWindow", "Grand Piano"))
        self.piano_col.setText(_translate("MainWindow", "Piano Collection"))
        self.ac_guitar.setText(_translate("MainWindow", "Acoustic Guitar"))
        self.user_sb.setText(_translate("MainWindow", "<Your Soundbank>"))

